url: https://craftyclark.github.io
##enforce_ssl: 
baseurl: /portfolio/

#exclude: [Gemfile, Gemfile.lock]

# Site settings
title: Andrew Clark
email: andrewclark.ku@gmail.com
description: "Andrew Clark's Software Developer Portfolio. "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2863a6
  secondary: 259bc8
  secondary-dark: "203634"
  nav-bar: "868686"

# Team names, titles and social links
people:
- name: Andrew Clark
  pic: 1
  position: Software Developer
  social:
    - title: linkedin
      url: https://linkedin.com/in/andrewclarkKU
    - title: github
      url: https://github.com/craftyclark
    - title: twitter
      url: https://twitter.com/crafty_clark

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/andrewclarkKU
  - title: github
    url: https://github.com/craftyclark
  - title: twitter
    url: https://twitter.com/crafty_clark

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM


# Try merging all the css again and use native jekyll/sass minification
sass:
  sass_dir: _sass
  style: compressed


# GH-pages supported plugins
gems:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap


# jekyll-compress-html
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
